### ISSUE TITLE
Cannot restart in docker

### ISSUE THREAD

**Issue by zdnet** [Enalean/docker-tuleap-aio#33]
i run below cmd to start Tuleap in docker:
docker run --name tuleap -ti -e VIRTUAL_HOST=localhost -p 10060:80 -p 10443:443 -p 11022:22 -v ~/docker/tuleap:/data enalean/tuleap-aio

and then i stop this container and update /etc/tuleap/conf/local.inc to my specified port and restart.
found below error:
-------------------------------------------------
Start mysql
+ sleep 1
+ /usr/bin/python /usr/lib/python2.6/site-packages/supervisor/pidproxy.py /var/run/mysqld/mysqld.pid /usr/bin/mysqld_safe
170725 08:20:57 mysqld_safe Logging to '/var/lib/mysql/984ccfffc0cb.err'.
touch: cannot touch `/var/lib/mysql/984ccfffc0cb.err': No such file or directory
chmod: cannot access `/var/lib/mysql/984ccfffc0cb.err': No such file or directory
touch: cannot touch `/var/lib/mysql/984ccfffc0cb.err': No such file or directory
chown: cannot access `/var/lib/mysql/984ccfffc0cb.err': No such file or directory
170725 08:20:57 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
170725 08:20:58 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended
++ egrep '^\$sys_dbpasswd' /etc/tuleap/conf/database.inc
++ sed -e 's/^\$sys_dbpasswd="\(.*\)";$/\1/'
+ mysql -ucodendiadm -pwb0fZgKUmP647tu -e 'show databases'
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)
+ echo 'Wait for the db'
Wait for the db
+ sleep 1
++ egrep '^\$sys_dbpasswd' /etc/tuleap/conf/database.inc
++ sed -e 's/^\$sys_dbpasswd="\(.*\)";$/\1/'
+ mysql -ucodendiadm -pwb0fZgKUmP647tu -e 'show databases'
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)
+ echo 'Wait for the db'
Wait for the db
+ sleep 1
--------------------------------------------------

any settings need to update? or any idea about this Mysql connection issue?

**Comment by j-mi-jim** [comment]
i have the same issue.

**Comment by vaceletm** [comment]
Issue was fixed as described in #35

**Comment by r0ots** [comment]
I am still having the issue, described here (not the one in #35 ). I can start a tuleap docker, it works. But then I stop and restart my docker and have the "can't connect to local MySQL" thing. 
I tried to hack and paste the password directly in mysql-utils.sh, but it worked.
