### ISSUE TITLE
Problem building and/or running Tuleap container

### ISSUE THREAD

**Issue by jlncrnt** [Enalean/docker-tuleap-aio#38]
Hi, 

Neither building nor running works for me. When I git clone and `docker build -t tuleap .` in the cloned dir, I get :
```
https://tuleap.net/pub/tuleap/yum/rhel/6/stable/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.
To address this issue please refer to the below knowledge base article 

https://access.redhat.com/articles/1320623

If above article doesn't help to resolve this issue please open a ticket with Red Hat Support.

Error: Cannot retrieve repository metadata (repomd.xml) for repository: Tuleap. Please verify its path and try again
```
And if I run : 
`docker run -ti -e VIRTUAL_HOST=localhost -p 80:80 -p 443:443 -p 22:22 -v tuleap-data:/data enalean/tuleap-aio`

as instructed for testing, I get a never ending:

```ERROR 1045 (28000): Access denied for user 'codendiadm'@'localhost' (using password: YES)```

message.

Do I miss something ? 

Docker version 17.10.0-ce, build f4ffd25 on Ubuntu 16.04

**Comment by tcottier-enalean** [comment]
Hi, we had some issues this morning with our repo. This should be solved now. You can have a look at this ticket: https://tuleap.net/plugins/tracker/?aid=10752

**Comment by bargacha** [comment]
Hi !
The issue is not solved for me. I have the same issue with the same configuration as jlncrnt. I have a never ending message :

```
++ egrep '^\$sys_dbpasswd' /etc/tuleap/conf/database.inc
++ sed -e 's/^\$sys_dbpasswd="\(.*\)";$/\1/'
+ mysql -ucodendiadm '-p$sys_dbpasswd='\''NpY9enQDROpax8p'\'';' -e 'show databases'
ERROR 1045 (28000): Access denied for user 'codendiadm'@'localhost' (using password: YES)
+ echo 'Wait for the db'
Wait for the db
+ sleep 1
```
For information ONLY : 

I tried the full installation in aws centos 6 server (with, of course, modified route tables), and I have similar issue when I check httpd error logs. Here what I see;

[Sun Oct 22 15:20:29 2017] [error] [client 77.136.87.85] PHP Warning:  mysql_connect(): Access denied for user 'codendiadm'@'localhost' (using password: YES) in /usr/share/tuleap/src/common/dao/include/DataAccess.class.php on line 112
[Sun Oct 22 15:20:29 2017] [error] [client 77.136.87.85] PHP Warning:  mysql_error() expects parameter 1 to be resource, boolean given in /usr/share/tuleap/src/common/dao/include/DataAccess.class.php on line 91
Other blabla ..

I have a blank page there http://ec2-35-176-239-73.eu-west-2.compute.amazonaws.com/

Container on docker / ubuntu 16.04
Aws server : centos 6.9; network is well configured, I can ping the web server (port 80/443).

I'm trying to install it since 4 days. I googled this issue many times and I did not find a clear solution. (I'm currently trying to modify db)

Thanks for all ! Impatient to use you app :)

**Comment by bargacha** [comment]
It seams that this post is a clone. The issue is already noticed there : https://github.com/Enalean/docker-tuleap-aio/issues/35 

Have a good day !

**Comment by vaceletm** [comment]
There are 2 issues there.
The build one was related to the rpm repositories availability and should be ok since last week
Once the issue described in #35 is confirmed fixed everything should be OK.

**Comment by jlncrnt** [comment]
It's working now. Thank you.
